version: 0.0
os: linux
files:
  - source: /
    destination: /opt/nodejs/PCAI-Frontend
hooks:
  BeforeInstall:
    - location: /awsdeploy/permissions
      timeout: 300
      runas: root
    - location: awsdeploy/before-install
      timeout: 300
      runas: root
  AfterInstall:
    - location: /awsdeploy/application-start
      timeout: 300
      runas: root
